apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-processor
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: queue-processor
  template:
    metadata:
      labels:
        app: queue-processor
    spec:
      initContainers:
        - name: init-wait-for-rabbitmq
          image: busybox
          command:
            [
              "sh",
              "-c",
              'until nc -z 192.168.1.163 5672; do echo "waiting for rabbitmq"; sleep 2; done;',
            ]
      containers:
        - name: worker-app
          image: boldo42/rain-dms-ocr-worker:latest
          imagePullPolicy: Always
          env:
            - name: REQUESTS_CA_BUNDLE
              value: "/usr/local/share/ca-certificates/ext-ca.crt"

            - name: OPENBLAS_CORETYPE
              value: "Haswell"   
            - name: OMP_NUM_THREADS
              value: "6"
            - name: MKL_NUM_THREADS
              value: "6"
            - name: OPENBLAS_NUM_THREADS
              value: "6"
          envFrom:
            - secretRef:
                name: app-env
          volumeMounts:
            - name: cert-vol
              mountPath: /usr/local/share/ca-certificates/ext-ca.crt
              subPath: ext-ca.crt
      volumes:
        - name: cert-vol
          secret:
            secretName: external-server-cert