apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: deny-app-policy
spec:
  namespaceSelector: '!has(projectcalico.org/name) || (projectcalico.org/name not in {"calico-system", "kube-public", "kube-system", "tigera-operator"})'
  types:
    - Egress

  egress:
    # Allow all namespaces to communicate with DNS pods (UDP)
    - action: Allow
      protocol: UDP
      destination:
        selector: 'k8s-app == "kube-dns"'
        ports:
          - 53

    # Allow all namespaces to communicate with DNS pods (TCP)
    - action: Allow
      protocol: TCP
      destination:
        selector: 'k8s-app == "kube-dns"'
        ports:
          - 53

    # Allow TCP traffic to local LAN
    # Example: HTTP, HTTPS, SSH, databases, etc.
    - action: Allow
      protocol: TCP
      destination:
        nets:
          - 192.168.1.0/24

    # Allow UDP traffic to local LAN
    # Example: DNS, NTP, discovery protocols, etc.
    - action: Allow
      protocol: UDP
      destination:
        nets:
          - 192.168.1.0/24
