apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: app-env
      key: AMQP_URL
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-app-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: queue-processor

  minReplicaCount: 1

  # patched dynamically by your scaler-sync job
  maxReplicaCount: 1

  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: ocr_handling_input
        mode: QueueLength
        value: "10"
      authenticationRef:
        name: keda-trigger-auth-rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-processor
  namespace: default
  labels:
    app: queue-processor
spec:
  replicas: 1

  selector:
    matchLabels:
      app: queue-processor

  template:
    metadata:
      labels:
        app: queue-processor

    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: queue-processor

      initContainers:
        - name: init-wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              until nc -z 192.168.1.163 5672;
              do
                echo "waiting for rabbitmq";
                sleep 2;
              done;

      containers:
        - name: worker-app
          image: boldo42/rain-dms-ocr-worker:latest
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false

          env:
            - name: REQUESTS_CA_BUNDLE
              value: /usr/local/share/ca-certificates/ext-ca.crt

            # allocator tuning
            - name: MALLOC_ARENA_MAX
              value: "2"

            # OpenMP affinity
            - name: OMP_PROC_BIND
              value: "TRUE"

            - name: OMP_PLACES
              value: "cores"

          envFrom:
            - secretRef:
                name: app-env

          resources:
            requests:
              cpu: "1"
              memory: 2Gi

            limits:
              cpu: "8"
              memory: 4Gi

          volumeMounts:
            - name: cert-vol
              mountPath: /usr/local/share/ca-certificates/ext-ca.crt
              subPath: ext-ca.crt

            - name: dev-dri
              mountPath: /dev/dri

      volumes:
        - name: cert-vol
          secret:
            secretName: external-server-cert

        - name: dev-dri
          hostPath:
            path: /dev/dri
            type: Directory
