apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: app-env
      key: AMQP_URL
    - parameter: caCert
      name: certificate
      key: ca.crt
    - parameter: tlsClientCert
      name: certificate
      key: tls.crt
    - parameter: tlsClientKey
      name: certificate
      key: tls.key

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-app-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: queue-processor
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: ocr_handling_input
        mode: QueueLength
        value: "10"
        tls: "enable"
      authenticationRef:
        name: keda-trigger-auth-rabbitmq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-processor
  namespace: default
  labels:
    app: queue-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-processor
  template:
    metadata:
      labels:
        app: queue-processor
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: queue-processor

      initContainers:
        - name: init-wait-for-rabbitmq
          image: nicolaka/netshoot
          env:
            - name: SERVER_IP
              valueFrom:
                secretKeyRef:
                  name: rain-dms-env
                  key: SERVER_IP
          command:
            - sh
            - -c
            - |
              until nc -zv "$SERVER_IP" 5671; do
                echo "waiting for rabbitmq"
                sleep 2
              done

      containers:
        - name: worker-app
          image: boldo42/rain-dms-ocr-worker:latest
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false

          env:
            - name: MALLOC_ARENA_MAX
              value: "2"
            - name: OMP_PROC_BIND
              value: "TRUE"
            - name: OMP_PLACES
              value: "cores"
            - name: NODE_EXTRA_CA_CERTS
              value: /ca/ca.crt

          envFrom:
            - secretRef:
                name: rain-dms-env
            - secretRef:
                name: app-env

          resources:
            requests:
              cpu: "3"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 6Gi

          volumeMounts:
            - name: cert-vol
              mountPath: /certs
              readOnly: true
            - name: ca-vol
              mountPath: /ca
              readOnly: true

      volumes:
        - name: cert-vol
          secret:
            secretName: external-server-cert
        - name: ca-vol
          secret:
            secretName: custom-root-ca
            items:
              - key: ca
                path: ca.crt
