services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: "masterbenno"
      MEILI_DB_PATH: /meili_data
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "7701:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../temp:/var/www/uploads
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP default port
      - "15672:15672" # Management UI
      - "1883:1883" # MQTT port (must be exposed manually)
    environment:
      RABBITMQ_HOST: "%"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test:
        - CMD
        - rabbitmq-diagnostics
        - "-q"
        - ping
      retries: 3
      timeout: 5s
