services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "7001:80"
      - "7443:443"
      - "5671:5671"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs:ro
      - ./dist:/usr/share/nginx/html:ro
      - ./logs/nginx:/var/log/nginx
      - ./certs/rootCA.pem:/usr/local/share/ca-certificates/mkcert-rootCA.crt
    environment:
      - SERVER_IDENT_HEX_STRING=${SERVER_IDENT_HEX_STRING}
      - SERVER_IP=${SERVER_IP}
    depends_on:
      master:
        condition: service_started
      volume:
        condition: service_started
      filer:
        condition: service_started
      s3:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - internal-network-nginx-server
      - lan-network
      - internal-network-nginx-s3
      - internal-network-nginx-ocr
      - internal-network-rabbitmq

  server:
    image: boldo42/rain-dms-server
    container_name: server
    user: root
    volumes:
      - ./consume:/consume
      - ./certs/rootCA.pem:/usr/local/share/ca-certificates/rootCA.crt
      - ./certs:/certs:ro
    entrypoint: >
      sh -c "update-ca-certificates && bun run db && bun run dev"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/rain_dms
      - AMQP_URL=amqps://${RABBITMQ_USER}:${RABBITMQ_PASS}@nginx:5671
      - SERVER_IP=${SERVER_IP}
      - S3_ACCESS_KEY=${ACCESS_KEY_S3}
      - S3_SECRET_KEY=${SECRET_KEY_S3}
      - MAIN_ENCRYPTION_KEY=${MAIN_ENCRYPTION_KEY}
      - RABBITMQ_MANAGEMENT_URL=http://rabbitmq:15672
      - SERVER_IDENT_HEX_STRING=${SERVER_IDENT_HEX_STRING}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - NGINX_PORT=7443
      - DEFAULT_USERNAME=${DEFAULT_USERNAME}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
      - DEBUG_WATCHER=${DEBUG_WATCHER}
      - NODE_EXTRA_CA_CERTS=/certs/rootCA.pem
      - S3_VERBOSE=true
      - BUN_TLS_DIR=/certs

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/auth/validate-jwt"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
    depends_on:
      nginx:
        condition: service_started
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      s3:
        condition: service_healthy
    networks:
      - internal-network-nginx-server
      - internal-network-rabbitmq
      - internal-network-server

  ocr-worker:
    image: boldo42/rain-dms-ocr-worker
    container_name: ocr-worker
    user: root
    volumes:
      - ./certs/rootCA.pem:/usr/local/share/ca-certificates/rootCA.crt
      - ./certs:/certs:ro
    env_file:
      - .env
    environment:
      - AMQP_URL=amqps://${RABBITMQ_USER}:${RABBITMQ_PASS}@nginx:5671
      - S3_ACCESS_KEY=${ACCESS_KEY_S3}
      - S3_SECRET_KEY=${SECRET_KEY_S3}
      - MAIN_ENCRYPTION_KEY=${MAIN_ENCRYPTION_KEY}
      - RABBITMQ_MANAGEMENT_URL=https://rabbitmq:15671
      - SERVER_IDENT_HEX_STRING=${SERVER_IDENT_HEX_STRING}
      - NGINX_PORT=7443
      - DEFAULT_USERNAME=${DEFAULT_USERNAME}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
      - NODE_EXTRA_CA_CERTS=/certs/rootCA.pem
      - S3_VERBOSE=true
      - BUN_TLS_DIR=/certs

    depends_on:
      rabbitmq:
        condition: service_healthy
      s3:
        condition: service_healthy
    networks:
      - internal-network-nginx-ocr
      - internal-network-rabbitmq

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rain_dms
    volumes:
      - postgres_data:/var/lib/postgresql/data

    entrypoint: >
      sh -c "docker-entrypoint.sh postgres &
            until pg_isready -U postgres; do sleep 1; done &&
            psql -U postgres -c \"ALTER USER postgres PASSWORD '$$POSTGRES_PASSWORD';\" &&
            wait"

    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d rain_dms"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped
    networks:
      - internal-network-server

  master:
    image: chrislusf/seaweedfs
    container_name: seaweed-master
    command: "master -ip.bind=0.0.0.0 -metricsPort=9324 -mdir=/data"
    volumes:
      - seaweed_master_data:/data
    networks:
      - internal-network-s3

  volume:
    image: chrislusf/seaweedfs
    container_name: seaweed-volume
    command: 'volume -master="master:9333" -ip.bind=0.0.0.0 -port=8080 -metricsPort=9325 -dir=/data -max=100'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "weed status -port=8080 | grep -q '正常' || weed status -port=8080 | grep -q 'OK' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - seaweed_volume_data:/data
    depends_on:
      - master
    networks:
      - internal-network-s3

  filer:
    image: chrislusf/seaweedfs
    container_name: seaweed-filer
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    tty: true
    stdin_open: true
    volumes:
      - seaweed_filer_data:/data
    depends_on:
      - master
      - volume
    networks:
      - internal-network-s3

  s3:
    image: chrislusf/seaweedfs
    container_name: seaweed-s3
    environment:
      - SEAWEEDFS_S3_KEY=${ACCESS_KEY_S3}
      - SEAWEEDFS_S3_SECRET=${SECRET_KEY_S3}
      - WEED_JWT_FILER_SIGNING_KEY=${SECRET_KEY_S3}
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9327 -allowEmptyFolder=true'
    depends_on:
      - master
      - volume
      - filer
    healthcheck:
      test: ["CMD", "weed", "download", "-server=localhost:8333", ""]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s
    networks:
      - internal-network-s3
      - internal-network-nginx-s3

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./certs:/etc/rabbitmq/certs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - internal-network-rabbitmq

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    volumes:
      - meili_data:/meili_data
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    restart: always
    networks:
      - internal-network-server

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "8082:8080"
    secrets:
      - source: users
        target: /data/users.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle_data:/data
    environment:
      - DOZZLE_AUTH=true
      - enable-shell=true
      - DOZZLE_AUTH_PROVIDER=simple

secrets:
  users:
    file: config/users-dozzle.yml

networks:
  lan-network:
    driver: bridge

  internal-network-server:
    driver: bridge
    internal: true

  internal-network-rabbitmq:
    driver: bridge
    internal: true

  internal-network-nginx-s3:
    driver: bridge
    internal: true

  internal-network-s3:
    driver: bridge
    internal: true

  internal-network-nginx-server:
    driver: bridge
    internal: true

  internal-network-nginx-ocr:
    driver: bridge
    internal: true

volumes:
  postgres_data:
  seaweed_master_data:
  seaweed_volume_data:
  seaweed_filer_data:
  rabbitmq_data:
  meili_data:
  dozzle_data:
