user root;
events {}

http {
    include       /etc/nginx/mime.types; # Ensures images render in-browser instead of downloading
    default_type  application/octet-stream;

    server {
        listen 80;

        # Using root maps /uploads/ to /var/www/uploads/ automatically
        location /uploads/ {
            root /var/www;
            autoindex on;
        }
    }
}